## Ad Spent Data Cleaning

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Yusuf\OneDrive\Desktop\ad_spend.csv")
df

,spend_id,campaign_id,campaign_name,platform,channel,ad_group_id,date,impressions,clicks,spend,cpc,ctr
0,SPD000001,CMP0001,Google_Brand_Search,Google Ads,Paid Search,AG3615,2025-01-13,2063,149,386.91,2.59,0.0722
1,SPD000002,CMP0001,Google_Brand_Search,Google Ads,Paid Search,AG6514,2025-01-14,6416,188,573.60,3.05,0.0293
2,SPD000003,CMP0001,Google_Brand_Search,Google Ads,Paid Search,AG6635,2025-01-16,891,37,126.66,3.35,0.0415
3,SPD000004,CMP0001,Google_Brand_Search,Google Ads,Paid Search,AG9785,2025-01-17,1191,76,502.79,6.55,0.0638
4,SPD000005,CMP0001,Google_Brand_Search,Google Ads,Paid Search,AG5803,2025-02-14,769,19,143.62,7.42,0.0247
...,...,...,...,...,...,...,...,...,...,...,...,...
745,SPD000746,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,AG8835,2025-09-24,16732,425,144.53,0.34,0.0254
746,SPD000747,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,AG2852,2025-09-26,4224,177,120.99,0.68,0.0419
747,SPD000748,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,AG3611,2025-10-29,649,32,24.21,0.75,0.0493
748,SPD000749,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,AG8178,2025-11-02,716,21,20.04,0.92,0.0293
749,SPD000750,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,AG1472,2025-12-18,2921,71,31.28,0.44,0.0243

In [4]:
print(df.columns.tolist())

['spend_id', 'campaign_id', 'campaign_name', 'platform', 'channel', 'ad_group_id', 'date', 'impressions', 'clicks', 'spend', 'cpc', 'ctr']

In [5]:
df.drop(columns=['spend_id', 'ad_group_id','cpc', 'ctr'], inplace=True)

In [6]:
df

,campaign_id,campaign_name,platform,channel,date,impressions,clicks,spend
0,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-13,2063,149,386.91
1,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-14,6416,188,573.60
2,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-16,891,37,126.66
3,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-17,1191,76,502.79
4,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-02-14,769,19,143.62
...,...,...,...,...,...,...,...,...
745,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-09-24,16732,425,144.53
746,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-09-26,4224,177,120.99
747,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-10-29,649,32,24.21
748,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-11-02,716,21,20.04
749,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-12-18,2921,71,31.28

In [7]:
df.isnull().sum()

campaign_id      0
campaign_name    0
platform         0
channel          0
date             0
impressions      0
clicks           0
spend            0
dtype: int64

In [8]:
# Strip spaces from all string columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [9]:
df

,campaign_id,campaign_name,platform,channel,date,impressions,clicks,spend
0,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-13,2063,149,386.91
1,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-14,6416,188,573.60
2,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-16,891,37,126.66
3,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-01-17,1191,76,502.79
4,CMP0001,Google_Brand_Search,Google Ads,Paid Search,2025-02-14,769,19,143.62
...,...,...,...,...,...,...,...,...
745,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-09-24,16732,425,144.53
746,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-09-26,4224,177,120.99
747,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-10-29,649,32,24.21
748,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-11-02,716,21,20.04
749,CMP0027,Email_Promo_Flash_Sale,Email Marketing,Email,2025-12-18,2921,71,31.28

In [10]:
#checking duplicates
print(df.duplicated().sum())

0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    750 non-null    object
 1   campaign_name  750 non-null    object
 2   platform       750 non-null    object
 3   channel        750 non-null    object
 4   date           750 non-null    object
 5   impressions    750 non-null    int64
 6   clicks         750 non-null    int64
 7   spend          750 non-null    float64
dtypes: float64(1), int64(2), object(5)
memory usage: 47.0+ KB

In [12]:
#checking date values
df['date'].sample(10)

181    2025-05-28
710    2025-08-27
83     2025-12-27
145    2025-02-22
35     2025-03-06
81     2025-12-06
214    2025-09-05
95     2025-07-14
522    2025-10-16
10     2025-04-22
Name: date, dtype: object

In [13]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    750 non-null    object
 1   campaign_name  750 non-null    object
 2   platform       750 non-null    object
 3   channel        750 non-null    object
 4   date           750 non-null    datetime64[ns]
 5   impressions    750 non-null    int64
 6   clicks         750 non-null    int64
 7   spend          750 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 47.0+ KB

In [15]:
df['date'].duplicated().sum()

np.int64(432)

In [17]:
df.to_csv(r"C:\Users\Yusuf\OneDrive\Desktop\cleaned_ad_spend.csv", index=False)