## Conversions Data Cleaning

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv(r"C:\Users\Yusuf\OneDrive\Desktop\conversions.csv")
df

,conversion_id,user_id,conversion_timestamp,conversion_type,order_id,revenue,product_category,customer_type
0,CNV0000001,USR0010624,2025-11-24 11:13:49,signup,ORD955130,862.20,Education,New
1,CNV0000002,USR0001762,2025-11-09 14:27:17,purchase,ORD774619,521.98,SaaS Subscription,New
2,CNV0000003,USR0007391,2025-07-14 17:31:05,subscription,ORD946616,63.62,Home Goods,Returning
3,CNV0000004,USR0006166,2025-05-24 10:48:44,demo_request,ORD702567,999.36,Electronics,New
4,CNV0000005,USR0017949,2025-09-15 15:59:48,subscription,ORD731743,539.36,SaaS Subscription,Returning
...,...,...,...,...,...,...,...,...
7495,CNV0007496,USR0001779,2025-09-25 07:56:43,signup,ORD788449,271.08,Fashion,New
7496,CNV0007497,USR0003438,2025-09-24 03:07:35,subscription,ORD190301,854.76,SaaS Subscription,New
7497,CNV0007498,USR0015260,2025-03-27 18:52:38,signup,ORD167702,742.87,SaaS Subscription,New
7498,CNV0007499,USR0005121,2025-04-06 00:23:04,lead,ORD493910,130.07,SaaS Subscription,Returning
7499,CNV0007500,USR0005282,2025-06-29 12:28:20,purchase,ORD319743,654.24,Electronics,Returning

In [25]:
print(df.columns.tolist())

['conversion_id', 'user_id', 'conversion_timestamp', 'conversion_type', 'order_id', 'revenue', 'product_category', 'customer_type']

In [26]:
df.isnull().sum()

conversion_id           0
user_id                 0
conversion_timestamp    0
conversion_type         0
order_id                0
revenue                 0
product_category        0
customer_type           0
dtype: int64

In [27]:
# Strip spaces from all string columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [28]:
df

,conversion_id,user_id,conversion_timestamp,conversion_type,order_id,revenue,product_category,customer_type
0,CNV0000001,USR0010624,2025-11-24 11:13:49,signup,ORD955130,862.20,Education,New
1,CNV0000002,USR0001762,2025-11-09 14:27:17,purchase,ORD774619,521.98,SaaS Subscription,New
2,CNV0000003,USR0007391,2025-07-14 17:31:05,subscription,ORD946616,63.62,Home Goods,Returning
3,CNV0000004,USR0006166,2025-05-24 10:48:44,demo_request,ORD702567,999.36,Electronics,New
4,CNV0000005,USR0017949,2025-09-15 15:59:48,subscription,ORD731743,539.36,SaaS Subscription,Returning
...,...,...,...,...,...,...,...,...
7495,CNV0007496,USR0001779,2025-09-25 07:56:43,signup,ORD788449,271.08,Fashion,New
7496,CNV0007497,USR0003438,2025-09-24 03:07:35,subscription,ORD190301,854.76,SaaS Subscription,New
7497,CNV0007498,USR0015260,2025-03-27 18:52:38,signup,ORD167702,742.87,SaaS Subscription,New
7498,CNV0007499,USR0005121,2025-04-06 00:23:04,lead,ORD493910,130.07,SaaS Subscription,Returning
7499,CNV0007500,USR0005282,2025-06-29 12:28:20,purchase,ORD319743,654.24,Electronics,Returning

In [29]:
#checking duplicates
print(df.duplicated().sum())

0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   conversion_id         7500 non-null   object
 1   user_id               7500 non-null   object
 2   conversion_timestamp  7500 non-null   object
 3   conversion_type       7500 non-null   object
 4   order_id              7500 non-null   object
 5   revenue               7500 non-null   float64
 6   product_category      7500 non-null   object
 7   customer_type         7500 non-null   object
dtypes: float64(1), object(7)
memory usage: 468.9+ KB

In [31]:
df['conversion_timestamp'].sample(10)

5499    2025-03-11 02:09:06
787     2025-01-19 17:40:41
6831    2025-07-13 23:16:09
2323    2025-12-20 08:59:48
2390    2025-05-15 05:21:03
448     2025-06-15 23:14:10
7162    2025-03-22 23:03:19
4820    2025-01-10 20:59:52
2686    2025-08-01 23:57:03
2376    2025-07-17 20:56:29
Name: conversion_timestamp, dtype: object

In [32]:
df['conversion_timestamp'] = pd.to_datetime(df['conversion_timestamp'], errors='coerce')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   conversion_id         7500 non-null   object
 1   user_id               7500 non-null   object
 2   conversion_timestamp  7500 non-null   datetime64[ns]
 3   conversion_type       7500 non-null   object
 4   order_id              7500 non-null   object
 5   revenue               7500 non-null   float64
 6   product_category      7500 non-null   object
 7   customer_type         7500 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 468.9+ KB

In [34]:
df['conversion_timestamp'].duplicated().sum()

np.int64(39)

In [35]:
df.to_csv(r"C:\Users\Yusuf\OneDrive\Desktop\cleaned_conversions.csv", index=False)