## User touchpoints Data Cleaning

In [22]:
import pandas as pd

In [23]:
df = pd.read_csv(
    r"C:\Users\Yusuf\OneDrive\Desktop\user_touchpoints.csv",
    low_memory=False
)
df

,touchpoint_id,user_id,session_id,timestamp,source,medium,campaign_id,campaign_name,event_type,landing_page,device_type,country,city,utm_source,utm_medium,utm_campaign
0,TP00000001,USR0010771,SES57244013,2025-12-21 22:06:20,email,email,CMP0027,Email_Promo_Flash_Sale,page_view,/,mobile,US,Chicago,email,email,Email_Promo_Flash_Sale
1,TP00000002,USR0010771,SES78645672,2025-12-22 07:30:20,blog,content,NaN,NaN,page_view,/checkout,mobile,US,Chicago,blog,content,NaN
2,TP00000003,USR0010771,SES65642914,2025-12-22 10:01:20,google,organic,NaN,NaN,page_view,/checkout,mobile,US,Chicago,google,organic,NaN
3,TP00000004,USR0010771,SES10822385,2025-12-22 19:20:20,direct,none,NaN,NaN,page_view,/saas-pricing,mobile,US,Chicago,NaN,NaN,NaN
4,TP00000005,USR0013394,SES47239551,2025-03-19 09:41:35,google,cpc,CMP0001,Google_Brand_Search,click,/contact,desktop,GB,Birmingham,google,cpc,Google_Brand_Search
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74995,TP00074996,USR0008215,SES93277094,2050-11-26 20:38:13,referral,referral,NaN,NaN,page_view,/login,tablet,SG,Singapore,NaN,NaN,NaN
74996,TP00074997,USR0008215,SES11530756,2051-01-03 15:58:13,google,organic,NaN,NaN,add_to_cart,/electronics,tablet,SG,Singapore,google,organic,NaN
74997,TP00074998,USR0008215,SES70446770,2051-02-13 19:40:13,google,organic,NaN,NaN,page_view,/blog/product-review,tablet,SG,Singapore,google,organic,NaN
74998,TP00074999,USR0008215,SES90868222,2051-03-06 07:40:13,direct,none,NaN,NaN,click,/blog/product-review,tablet,SG,Singapore,NaN,NaN,NaN
74999,TP00075000,USR0008215,SES36353379,2051-03-30 19:16:13,bing,organic,NaN,NaN,page_view,/login,tablet,SG,Singapore,bing,organic,NaN

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   touchpoint_id  75000 non-null  object
 1   user_id        75000 non-null  object
 2   session_id     75000 non-null  object
 3   timestamp      75000 non-null  object
 4   source         75000 non-null  object
 5   medium         75000 non-null  object
 6   campaign_id    31554 non-null  object
 7   campaign_name  31554 non-null  object
 8   event_type     75000 non-null  object
 9   landing_page   75000 non-null  object
 10  device_type    75000 non-null  object
 11  country        75000 non-null  object
 12  city           75000 non-null  object
 13  utm_source     63042 non-null  object
 14  utm_medium     63042 non-null  object
 15  utm_campaign   29996 non-null  object
dtypes: object(16)
memory usage: 9.2+ MB

In [25]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [26]:
df.isnull().sum().sort_values(ascending=False)

utm_campaign     45004
campaign_id      43446
campaign_name    43446
utm_source       11958
utm_medium       11958
touchpoint_id        0
user_id              0
session_id           0
timestamp            0
source               0
medium               0
event_type           0
landing_page         0
device_type          0
country              0
city                 0
dtype: int64

In [27]:
df.columns

Index(['touchpoint_id', 'user_id', 'session_id', 'timestamp', 'source',
       'medium', 'campaign_id', 'campaign_name', 'event_type', 'landing_page',
       'device_type', 'country', 'city', 'utm_source', 'utm_medium',
       'utm_campaign'],
      dtype='object')

In [28]:
df['source'].equals(df['utm_source'])

False

In [29]:
df['medium'].equals(df['utm_medium'])

False

In [30]:
df['campaign_name'].equals(df['utm_campaign'])

False

In [31]:
df.drop(
    columns=['utm_source', 'utm_medium', 'utm_campaign', 'touchpoint_id'],
    inplace=True
)

In [32]:
df

,user_id,session_id,timestamp,source,medium,campaign_id,campaign_name,event_type,landing_page,device_type,country,city
0,USR0010771,SES57244013,2025-12-21 22:06:20,email,email,CMP0027,Email_Promo_Flash_Sale,page_view,/,mobile,US,Chicago
1,USR0010771,SES78645672,2025-12-22 07:30:20,blog,content,NaN,NaN,page_view,/checkout,mobile,US,Chicago
2,USR0010771,SES65642914,2025-12-22 10:01:20,google,organic,NaN,NaN,page_view,/checkout,mobile,US,Chicago
3,USR0010771,SES10822385,2025-12-22 19:20:20,direct,none,NaN,NaN,page_view,/saas-pricing,mobile,US,Chicago
4,USR0013394,SES47239551,2025-03-19 09:41:35,google,cpc,CMP0001,Google_Brand_Search,click,/contact,desktop,GB,Birmingham
...,...,...,...,...,...,...,...,...,...,...,...,...
74995,USR0008215,SES93277094,2050-11-26 20:38:13,referral,referral,NaN,NaN,page_view,/login,tablet,SG,Singapore
74996,USR0008215,SES11530756,2051-01-03 15:58:13,google,organic,NaN,NaN,add_to_cart,/electronics,tablet,SG,Singapore
74997,USR0008215,SES70446770,2051-02-13 19:40:13,google,organic,NaN,NaN,page_view,/blog/product-review,tablet,SG,Singapore
74998,USR0008215,SES90868222,2051-03-06 07:40:13,direct,none,NaN,NaN,click,/blog/product-review,tablet,SG,Singapore
74999,USR0008215,SES36353379,2051-03-30 19:16:13,bing,organic,NaN,NaN,page_view,/login,tablet,SG,Singapore

In [33]:
df.to_csv(r"C:\Users\Yusuf\OneDrive\Desktop\cleaned_user_touchpoints.csv", index=False)